# Generated by Django 2.2.3 on 2019-08-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('detail', models.TextField(max_length=100)),
                ('toggle', models.BooleanField()),
            ],
        ),
    ]
